config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :parties
  resources :beverages
  resources :friendships, only: [:new, :destroy]
  get "/friendships/:id", to: "friendships#destroy"
  get "/add_friends", to: "friendships#add_friends"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/beverage.rb
class Beverage < ApplicationRecord
  belongs_to :meeting
  belongs_to :drink
  validates :drink, presence: true
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  def create
    @meeting = Meeting.find(params[:beverage][:meeting_id])
    @party = @meeting.party
    if (params[:beverage][:drink_id]).empty?
      redirect_to request.referer
    else
      @drink = Drink.find(params[:beverage][:drink_id])
      @beverage = Beverage.new(beverage_params)
      @beverage.drink = @drink

      respond_to do |format|
        if @beverage.save
          PartyChannel.broadcast_to(
            @party,
            render_to_string(partial: "buddy.html", locals: { users: @party.users, party: @party })
          )
          format.html { redirect_to request.referer }
          format.json { render json: json_response }
        else
          format.html { render 'parties/show' }
          format.json
        end
      end
    end
    authorize(Beverage)
  end

  def destroy
    @beverage = Beverage.find(params[:id])
    @meeting = @beverage.meeting
    @party = @meeting.party
    authorize(@beverage)
    respond_to do |format|
      if @beverage.destroy
        PartyChannel.broadcast_to(
          @party,
          render_to_string(partial: "buddy.html", locals: { users: @party.users, party: @party })
        )
        format.json { render json: json_response }
      end
    end
    # redirect_to request.referer
  end

  def calculate_rates
    @alcool_rate = @meeting.sobriaty[:alcool_rate]
    @time_to_dedrunk = @meeting.sobriaty[:time_format]
  end

  private

  def beverage_params
    params.require(:beverage).permit(:meeting_id, :drink_id)
  end

  def json_response
    calculate_rates

    {
      editable_list_partial: render_to_string(partial: 'beverages/list.html', locals: { beverages: @meeting.beverages, editable: true }),
      list_partial: render_to_string(partial: 'beverages/list.html', locals: { beverages: @meeting.beverages, editable: false }),
      alcool_rate_partial: render_to_string(partial: 'parties/alcool_rate.html', locals: { alcool_rate: @alcool_rate, is_in_modal: false }),
      alcool_rate_partial_in_modal: render_to_string(partial: 'parties/alcool_rate.html', locals: { alcool_rate: @alcool_rate, is_in_modal: true }),
      time_to_dedrunk_partial: @time_to_dedrunk
    }
  end
end

app/views/beverages/_buddy.html.erb
<% users.each_with_index do |friendship, index| %>
  <div class = "position-relative round-buddy <%#= colors[index] %>" id="badges-from-show" >
    <% if friendship.photo.attached? %>
      <%= cl_image_tag friendship.photo.key, height: 100, width: 100, crop: :fill %>
    <% else %>
      <%= friendship.initials %>
    <% end %>
    <div class="friendship_alcool_rate top-0 start-100 translate-middle p-2 <%= friendship.drunked_color(party) %> border border-light rounded-circle " >
      <div class= "rounded-badges" >
        <%=friendship.user_alcool_rate(party)%>
      </div>
    </div>
  </div>
<% end %>

app/views/beverages/_list.html.erb
<ul>
    <% beverages.each do |beverage|%>
      <li>
        <%= beverage.drink.alcool_type %>

        <% if local_assigns[:editable] == true %>
          <%= link_to beverage_path(beverage), data: { action: 'beverages#delete' } do %>
            <svg xmlns="http://www.w3.org/2000/svg" height="24px" fill="none" viewBox="0 0 24 24" stroke="red">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          <% end %>
        <% end %>
      </li>
    <% end %>
</ul>