config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :parties
  resources :beverages
  resources :friendships, only: [:new, :destroy]
  get "/friendships/:id", to: "friendships#destroy"
  get "/add_friends", to: "friendships#add_friends"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user_one, class_name: "User"
  belongs_to :user_two, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def new
    @users = User.all.where.not(id: current_user.id)
    @friendship = Friendship.new
    authorize(@friendship)
  end

  def add_friends
    @current_friends = current_user.friends.pluck(:id)
    if params[:users]
      @current_friends.reject! { |friends| params[:users].include?(friends) }
      @current_friends.each { |friend| Friendship.find_by(user_one_id: current_user.id, user_two_id: friend.to_i).destroy }
      params[:users].each do |user|
        if Friendship.find_by(user_one_id: current_user.id, user_two_id: User.find(user.to_i).id).nil?
          Friendship.create!(user_one_id: current_user.id, user_two_id: User.find(user.to_i).id)
        end
      end
    else
      Friendship.where(user_one_id: current_user.id).destroy_all
    end
    Friendship.last.nil? ? @friendship = Friendship.new : @friendship = Friendship.last
    authorize(@friendship)
    redirect_to dashboard_path
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    authorize(@friendship)
    @friendship.destroy
    redirect_to dashboard_path
  end
end

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/new.html.erb
<div class="container custom-container">
  <div class="title-new-friendship">
    <h2>Select your friends</h2>
  </div>
  <% array = ["rd-purple", "rd-pink", "rd-corail", "rd-blue", "rd-acqua", "rd-red", "rd-orange", "rd-blue-clr"] %>
  <% colors = array.sample(@users.count) %>

  <div class="my-buddies">
    <%= form_tag add_friends_path, method: :get do |f| %>
      <div class="d-flex flex-wrap justify-content-between align-items-center mt-10 border-red">
        <% @users.each_with_index do |user, index| %>
          <%= label_tag user, class: "round-buddy #{colors[index]} #{'avatar-checked' if current_user.friends.include?(user)} new-form" do %>
            <% if user.photo.attached? %>
              <%= cl_image_tag user.photo.key, height: 100, width: 100, crop: :fill %>
            <% else %>
              <%= user.initials %>
            <% end %>
            <%= check_box_tag "users[]", user.id, checked = current_user.friends.include?(user)  %>
          <% end %>
        <% end %>
      </div>
       <%= submit_tag "Save", class:"btn-drunked main" %>
    <% end %>

    <div id="backdash" class="fas fa-arrow-left">
      <%= link_to "Back", dashboard_path %>
    </div>
  </div>
</div>