config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#landing'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :parties
  resources :beverages
  resources :friendships, only: [:new, :destroy]
  get "/friendships/:id", to: "friendships#destroy"
  get "/add_friends", to: "friendships#add_friends"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard.html.erb
<div class= "container" >
  <div class= "parties">
    <div class= "sous-title-1-dash">
      <h2> My last parties </h2>
    </div>
    <div class= "last-parties">
      <div class="link">
        <% current_user.parties.last(3).each do |party| %>
          <h5 class="d-flex align-items-center">
            <%= link_to party.name, party_path(party) %>
          </h5>
        <% end %>
      </div>
    </div>
  </div>
  <div class= "sous-title-2-dash">
    <h2><%= "My drinking buddies" %></h2>
    <div class="my-buddies">
      <div class="tag_item d-flex flex-wrap">
        <%= check_box_tag 'toggle_poubelle' %>
        <label for="toggle_poubelle">remove buddies</label>
        <% array = ["rd-purple", "rd-pink", "rd-corail", "rd-blue", "rd-acqua", "rd-red", "rd-orange", "rd-blue-clr"] %>
        <% colors = array.sample(current_user.friendships.count)%>
        <% current_user.friendships.each_with_index do |friendship, index| %>
          <div class = "round-buddy <%= colors[index] %>" >
            <% if friendship.user_two.photo.attached?%>
              <%= cl_image_tag friendship.user_two.photo.key, height: 100, width: 100, crop: :fill %>
            <% else %>
              <%= friendship.user_two.initials %>
            <% end %>
            <%= link_to friendship_path(friendship),
              method: :delete do  %>
              <i class="fas fa-minus-circle custom-circle"></i>
              <% end %>
          </div>
        <% end %>
        <div class="round-buddy-2">
        <%= link_to new_friendship_path, data: { turbolinks: 'false'} do %>
         <i class="fas fa-plus"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Let's party !", new_party_path, class: "btn-drunked main", data: {turbolinks: false} %>
</div>

app/views/pages/landing.html.erb
<div class="landing-container container">
    <div class= "text-container">
      <div class="title-landing">
        <h1>Drunked.</h1>
      </div>
      <h2>Drink and Drive home safely.</h2>
  </div>
  <div class="btn_landing">
    <%= link_to "Login", new_user_session_path, class: "btn-drunked btn-medium" %>
    <%= link_to "Signup", new_user_registration_path, class: "btn-drunked btn-medium" %>
  </div>
</div>